<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);LATEST</DefineConstants>
    <Configurations>Debug-1.29.1;Release-1.29.1;Debug-1.34.2;Release-1.34.2;Debug-1.37.1;Release-1.37.1;Debug-1.40.8;Release-1.40.8;Debug-1.42.1;Release-1.42.1;Debug-1.45.0;Release-1.45.0;Debug-1.45.1;Release-1.45.1</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <PluginId>Synapse</PluginId>
    <PluginName>Synapse</PluginName>
    <Author>Aeroluna</Author>
    <Version>1.2.0</Version>
    <GameVersion>1.45.1</GameVersion>
    <Description>Connect with other players for live events with chatting, leaderboards, and synchronized play.</Description>
  </PropertyGroup>
  <ItemGroup>
    <DependsOn Include="BeatSaberMarkupLanguage" Version="^1.6.3"/>
    <DependsOn Include="BSIPA" Version="^4.2.2"/>
    <DependsOn Include="SiraUtil" Version="^3.0.5"/>
  </ItemGroup>

  <ItemDefinitionGroup>
    <Reference Private="False"/>
  </ItemDefinitionGroup>
  <ItemGroup>
    <Reference Include="0Harmony" HintPath="$(BeatSaberDir)\Libs\0Harmony.dll"/>
    <Reference Include="BeatmapCore" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\BeatmapCore.dll"/>
    <Reference Include="BeatSaber.Multiplayer.Core" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.Multiplayer.Core.dll"/>
    <Reference Include="BeatSaber.ViewSystem" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\BeatSaber.ViewSystem.dll" Publicize="true"/>
    <Reference Include="BeatSaberMarkupLanguage" HintPath="$(BeatSaberDir)\Plugins\BSML.dll"/>
    <Reference Include="BGLib.AppFlow" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\BGLib.AppFlow.dll"/>
    <Reference Include="BGLib.UnityExtension" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\BGLib.UnityExtension.dll"/>
    <Reference Include="BGNet" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\BGNet.dll"/>
    <Reference Include="BGNetCore" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\BGNetCore.dll"/>
    <Reference Include="Colors" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Colors.dll"/>
    <Reference Include="Core" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Core.dll"/>
    <Reference Include="DataModels" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\DataModels.dll" Publicize="true"/>
    <Reference Include="GameplayCore" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\GameplayCore.dll" Publicize="true"/>
    <Reference Include="Hive.Versioning" HintPath="$(BeatSaberDir)\Libs\Hive.Versioning.dll"/>
    <Reference Include="HMLib" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\HMLib.dll" Publicize="true"/>
    <Reference Include="HMUI" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\HMUI.dll" Publicize="true"/>
    <Reference Include="HMRendering" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\HMRendering.dll" Publicize="true"/>
    <Reference Include="Interactable" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Interactable.dll"/>
    <Reference Include="IPA.Loader" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\IPA.Loader.dll"/>
    <Reference Include="Main" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Main.dll" Publicize="true"/>
    <Reference Include="MediaLoader" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\MediaLoader.dll"/>
    <Reference Include="OculusStudios.Platform.Core" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\OculusStudios.Platform.Core.dll" />
    <Reference Include="Networking" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Networking.dll"/>
    <Reference Include="Newtonsoft.Json" HintPath="$(BeatSaberDir)\Libs\Newtonsoft.Json.dll"/>
    <Reference Include="PlatformUserModel" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\PlatformUserModel.dll"/>
    <Reference Include="Rendering" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Rendering.dll" Publicize="true"/>
    <Reference Include="SegmentedControl" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\SegmentedControl.dll" Publicize="true"/>
    <Reference Include="SiraUtil" HintPath="$(BeatSaberDir)\Plugins\SiraUtil.dll"/>
    <Reference Include="Transitions" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Transitions.dll" Publicize="true"/>
    <Reference Include="Tweening" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Tweening.dll"/>
    <Reference Include="Unity.TextMeshPro" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Unity.TextMeshPro.dll"/>
    <Reference Include="UnityEngine.AnimationModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.AnimationModule.dll"/>
    <Reference Include="UnityEngine.AssetBundleModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.AssetBundleModule.dll"/>
    <Reference Include="UnityEngine.AudioModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.AudioModule.dll"/>
    <Reference Include="UnityEngine.CoreModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.CoreModule.dll"/>
    <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.ImageConversionModule.dll"/>
    <Reference Include="UnityEngine.IMGUIModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.IMGUIModule.dll"/>
    <Reference Include="UnityEngine.JSONSerializeModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.JSONSerializeModule.dll"/>
    <Reference Include="UnityEngine.InputLegacyModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.InputLegacyModule.dll"/>
    <Reference Include="UnityEngine.ParticleSystemModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.ParticleSystemModule.dll"/>
    <Reference Include="UnityEngine.UI" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.UI.dll"/>
    <Reference Include="UnityEngine.UIModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.UIModule.dll"/>
    <Reference Include="UnityEngine.UnityWebRequestModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.UnityWebRequestModule.dll"/>
    <Reference Include="UnityEngine.UnityWebRequestTextureModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.UnityWebRequestTextureModule.dll"/>
    <Reference Include="UnityEngine.VideoModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.VideoModule.dll"/>
    <Reference Include="UnityEngine.VRModule" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\UnityEngine.VRModule.dll"/>
    <Reference Include="Zenject" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Zenject.dll"/>
    <Reference Include="Zenject-usage" HintPath="$(BeatSaberDir)\Beat Saber_Data\Managed\Zenject-usage.dll"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Synapse.Networking\Synapse.Networking.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BeatSaberModdingTools.Tasks.Luna" Version="2.1.0"/>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.*"/>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.34.2"/>
    <PackageReference Include="LunaBSMod.Tasks" Version="1.1.0"/>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556"/>
  </ItemGroup>
</Project>
